Refactor mediator, runner
skni-kod/Kubexecutor pull request #19
Opened 2023-05-25 12:04 UTC by mherda64

2023-05-25 13:14 UTC, Adrian-99 requested changes
Great work, just a few things to change

2023-05-25 13:14 UTC, Adrian-99 commented on mediator/src/main/kotlin/pl/edu/prz/kod/mediator/adapters/http/MediatorHttpHandler.kt
>      private val executeResponseLens = Jackson.autoBody<CodeResponse>().toLens()
Those objects are created in `Leneses` class already, so I guess they should be used there.

2023-05-25 13:14 UTC, Adrian-99 commented on mediator/src/main/kotlin/pl/edu/prz/kod/mediator/domain/RunnerManager.kt
> +                    String.format(configuration.runnerPathFormat, runner) + "/execute"
How about moving `Constants` class to common and using its `EXECUTE_PATH` and `STATUS_PATH` variables here?

2023-05-25 13:14 UTC, Adrian-99 commented on runner/src/main/kotlin/pl/edu/prz/kod/runner/application/Application.kt
> +                singleOf(::RunnerHttpHandler)
That `singleOf` looks cleaner than the rest of declarations above. Maybe they could be replaced by `singleOf`?

Same suggestion applies to mediator.

2023-05-25 13:14 UTC, Adrian-99 commented on mediator/src/main/kotlin/pl/edu/prz/kod/mediator/application/Configuration.kt
> +    val httpPort: Int = BaseEnvironmentVariable.getIntValue("HTTP_PORT", 8081),
The `BaseEnvironmentVariable` class could be renamed to `EnvironmentVariable` now. Earlier it was named like this to avoid name duplication, but that's not the case anymore.

2023-05-25 13:14 UTC, Adrian-99 commented on mediator/src/main/kotlin/pl/edu/prz/kod/mediator/domain/RunnerManager.kt
> +        ).status.successful
The acutally returned status should be checked here, as in previous PR I changed it that every status request returns status 200 (as the request itself is successful regardless of status, so it seems more appropriate for me).

2023-05-25 18:14 UTC, mherda64 commented on runner/src/main/kotlin/pl/edu/prz/kod/runner/application/Application.kt
> +                singleOf(::RunnerHttpHandler)
It certainly looks cleaner, though I'm afraid we can't define generic type there. I'll check it out.

2023-05-29 15:21 UTC, Adrian-99 approved these changes
Looks fine to me, good work

2023-05-29 15:21 UTC, merged